# Definición del grupo de servidores web (Cluster)
upstream web_cluster {
    server 192.168.56.11; # web1
    server 192.168.56.12; # web2
    server 192.168.56.13; # web3
}

server {
    listen 80;
    server_name localhost;

    location / {
        # Enviar todas las peticiones al grupo definido arriba
        proxy_pass http://web_cluster;
        # Pasar información del cliente real a los servidores web
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}