Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # --- CONFIGURACIÓN DEL BALANCEADOR (LB) ---
  config.vm.define "lb" do |lb|
    lb.vm.network "private_network", ip: "192.168.56.10" # IP privada interna
    lb.vm.hostname = "lb"
    lb.vm.provision "shell", path: "scripts/lb.sh" # Ejecuta el script de Nginx
    # Redirigir el puerto 9090 del PC real al 80 de la VM
    lb.vm.network "forwarded_port", guest: 80, host: 9090
    lb.vm.provider "virtualbox" do |vb|
      vb.name = "Cluster-LB"
      vb.memory = "512" # RAM optimizada para balanceo
    end
  end

  # --- CONFIGURACIÓN DE LOS 3 SERVIDORES WEB ---
  (1..3).each do |i|
    config.vm.define "web#{i}" do |web|
      web.vm.network "private_network", ip: "192.168.56.1#{i}"
      web.vm.hostname = "web#{i}"
      web.vm.provision "shell", path: "scripts/web.sh" # Instala Apache y PHP
      web.vm.provider "virtualbox" do |vb|
        vb.name = "Cluster-Web-#{i}"
        vb.memory = "1024" # RAM necesaria para procesar PHP
      end
    end
  end

  # --- CONFIGURACIÓN DE LA BASE DE DATOS (DB) ---
  config.vm.define "db" do |db|
    db.vm.network "private_network", ip: "192.168.56.20"
    db.vm.hostname = "db"
    db.vm.provision "shell", path: "scripts/db.sh" # Configura MySQL
    db.vm.provider "virtualbox" do |vb|
      vb.name = "Cluster-DB"
      vb.memory = "2048" # Mayor RAM para el motor de datos
    end
  end
end